package com.java.yxt.logger.feign.entity;

import com.alibaba.fastjson.JSONObject;

import java.io.Serializable;

public class OperationObject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operate_object.object_type
     *
     * @mbg.generated
     */
    private Integer objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operate_object.objectname
     *
     * @mbg.generated
     */
    private String objectname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operate_object.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_operate_object.db_name
     *
     * @mbg.generated
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_operate_object
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operate_object.object_type
     *
     * @return the value of t_operate_object.object_type
     *
     * @mbg.generated
     */
    public Integer getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operate_object.object_type
     *
     * @param objectType the value for t_operate_object.object_type
     *
     * @mbg.generated
     */
    public void setObjectType(Integer objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operate_object.objectname
     *
     * @return the value of t_operate_object.objectname
     *
     * @mbg.generated
     */
    public String getObjectname() {
        return objectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operate_object.objectname
     *
     * @param objectname the value for t_operate_object.objectname
     *
     * @mbg.generated
     */
    public void setObjectname(String objectname) {
        this.objectname = objectname == null ? null : objectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operate_object.table_name
     *
     * @return the value of t_operate_object.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operate_object.table_name
     *
     * @param tableName the value for t_operate_object.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_operate_object.db_name
     *
     * @return the value of t_operate_object.db_name
     *
     * @mbg.generated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_operate_object.db_name
     *
     * @param dbName the value for t_operate_object.db_name
     *
     * @mbg.generated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }
    @Override
    public String toString() {
        String jsonStr = JSONObject.toJSONString(this);
        return jsonStr ;
    }
}