package com.java.yxt.logger.feign.entity;

import com.alibaba.fastjson.JSONObject;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class StaffOperationLog implements Serializable {
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty(example = "2020-07-10 13:30:41")
    private Date operateTimeStart;
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty(example = "2020-07-10 13:30:41")
    private Date operateTimeEnd;
    @ApiModelProperty(example = "2020-07-10 13:30:41")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTimeStart;
    @ApiModelProperty(example = "2020-07-10 13:30:41")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTimeEnd;

    private String objectname;
    private String tableName;
    private String dbName;
    private String extendId;
    private String extendName;

    public String getExtendId() {
        return extendId;
    }

    public void setExtendId(String extendId) {
        this.extendId = extendId;
    }

    public String getExtendName() {
        return extendName;
    }

    public void setExtendName(String extendName) {
        this.extendName = extendName;
    }

    public String getObjectname() {
        return objectname;
    }

    public void setObjectname(String objectname) {
        this.objectname = objectname == null ? null : objectname.trim();
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    public String getDbName() {
        return dbName;
    }

    public void setDbName(String dbName) {
        this.dbName = dbName ==null ? null :dbName.trim();
    }

    public Date getOperateTimeStart() {
        return operateTimeStart;
    }

    public void setOperateTimeStart(Date operateTimeStart) {
        this.operateTimeStart = operateTimeStart;
    }

    public Date getOperateTimeEnd() {
        return operateTimeEnd;
    }

    public void setOperateTimeEnd(Date operateTimeEnd) {
        this.operateTimeEnd = operateTimeEnd;
    }

    public Date getCreateTimeStart() {
        return createTimeStart;
    }

    public void setCreateTimeStart(Date createTimeStart) {
        this.createTimeStart = createTimeStart;
    }

    public Date getCreateTimeEnd() {
        return createTimeEnd;
    }

    public void setCreateTimeEnd(Date createTimeEnd) {
        this.createTimeEnd = createTimeEnd;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.log_id
     *
     * @mbg.generated
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.object_type
     *
     * @mbg.generated
     */
    private Integer objectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.siteid
     *
     * @mbg.generated
     */
    private Long siteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.staff_name
     *
     * @mbg.generated
     */
    private String staffName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.operate_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(example = "2020-07-10 13:30:41")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.operate_type
     *
     * @mbg.generated
     */
    private Integer operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.objectid
     *
     * @mbg.generated
     */
    private Long objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.userid
     *
     * @mbg.generated
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.staff_id
     *
     * @mbg.generated
     */
    private Long staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(example = "2020-07-10 13:30:41")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.org_id
     *
     * @mbg.generated
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.department_id
     *
     * @mbg.generated
     */
    private Long departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.dept_name
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.origin_value
     *
     * @mbg.generated
     */
    private String originValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.new_value
     *
     * @mbg.generated
     */
    private String newValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_op_log.remark
     *
     * @mbg.generated
     */

    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_staff_op_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.log_id
     *
     * @return the value of t_staff_op_log.log_id
     *
     * @mbg.generated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.log_id
     *
     * @param logId the value for t_staff_op_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.object_type
     *
     * @return the value of t_staff_op_log.object_type
     *
     * @mbg.generated
     */
    public Integer getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.object_type
     *
     * @param objectType the value for t_staff_op_log.object_type
     *
     * @mbg.generated
     */
    public void setObjectType(Integer objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.siteid
     *
     * @return the value of t_staff_op_log.siteid
     *
     * @mbg.generated
     */
    public Long getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.siteid
     *
     * @param siteid the value for t_staff_op_log.siteid
     *
     * @mbg.generated
     */
    public void setSiteid(Long siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.staff_name
     *
     * @return the value of t_staff_op_log.staff_name
     *
     * @mbg.generated
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.staff_name
     *
     * @param staffName the value for t_staff_op_log.staff_name
     *
     * @mbg.generated
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.operate_time
     *
     * @return the value of t_staff_op_log.operate_time
     *
     * @mbg.generated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.operate_time
     *
     * @param operateTime the value for t_staff_op_log.operate_time
     *
     * @mbg.generated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.operate_type
     *
     * @return the value of t_staff_op_log.operate_type
     *
     * @mbg.generated
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.operate_type
     *
     * @param operateType the value for t_staff_op_log.operate_type
     *
     * @mbg.generated
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.objectid
     *
     * @return the value of t_staff_op_log.objectid
     *
     * @mbg.generated
     */
    public Long getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.objectid
     *
     * @param objectid the value for t_staff_op_log.objectid
     *
     * @mbg.generated
     */
    public void setObjectid(Long objectid) {
        this.objectid = objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.userid
     *
     * @return the value of t_staff_op_log.userid
     *
     * @mbg.generated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.userid
     *
     * @param userid the value for t_staff_op_log.userid
     *
     * @mbg.generated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.staff_id
     *
     * @return the value of t_staff_op_log.staff_id
     *
     * @mbg.generated
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.staff_id
     *
     * @param staffId the value for t_staff_op_log.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.create_time
     *
     * @return the value of t_staff_op_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.create_time
     *
     * @param createTime the value for t_staff_op_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.org_id
     *
     * @return the value of t_staff_op_log.org_id
     *
     * @mbg.generated
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.org_id
     *
     * @param orgId the value for t_staff_op_log.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.org_name
     *
     * @return the value of t_staff_op_log.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.org_name
     *
     * @param orgName the value for t_staff_op_log.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.department_id
     *
     * @return the value of t_staff_op_log.department_id
     *
     * @mbg.generated
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.department_id
     *
     * @param departmentId the value for t_staff_op_log.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.dept_name
     *
     * @return the value of t_staff_op_log.dept_name
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.dept_name
     *
     * @param deptName the value for t_staff_op_log.dept_name
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.origin_value
     *
     * @return the value of t_staff_op_log.origin_value
     *
     * @mbg.generated
     */
    public String getOriginValue() {
        return originValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.origin_value
     *
     * @param originValue the value for t_staff_op_log.origin_value
     *
     * @mbg.generated
     */
    public void setOriginValue(String originValue) {
        this.originValue = originValue == null ? null : originValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.new_value
     *
     * @return the value of t_staff_op_log.new_value
     *
     * @mbg.generated
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.new_value
     *
     * @param newValue the value for t_staff_op_log.new_value
     *
     * @mbg.generated
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue == null ? null : newValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_op_log.remark
     *
     * @return the value of t_staff_op_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_op_log.remark
     *
     * @param remark the value for t_staff_op_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
    @Override
    public String toString() {
        String jsonStr = JSONObject.toJSONString(this);
        return jsonStr ;
    }
}